# Usa una imagen base de Node.js
FROM node:20.16.0

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Compila TypeScript
RUN npm run build

# Expone el puerto
EXPOSE 5000

# Comando para correr la aplicación
CMD ["node", "dist/server.js"]
